### ISSUE TITLE
This works for me, but...

### ISSUE THREAD

**Issue by fade2gray** [0mWindyBug/KDP-compatible-driver-loader#8]
Windows 11 23H2

Thank you, this works for me as far as it resolves the problem of using an unsigned driver, but...

![Screenshot 2024-03-26 150110](https://github.com/0mWindyBug/KDP-compatible-driver-loader/assets/1332009/21ab6aa6-72d6-4341-906e-50f1ab6becf8)

![Screenshot 2024-03-26 150308](https://github.com/0mWindyBug/KDP-compatible-driver-loader/assets/1332009/66b77fbd-2f73-46fd-9da9-ec1fff142f13)

**Comment by 0mWindyBug** [comment]
Hey, this was sort of by design 
Intended for minifilter drivers so you don’t have to reinstall the INF file every time you want to load your driver , initially I deleted the key, I still have the functionality in the code ( the delete service function) . so if that suits your needs just call it from the unload routine , it’s probably right to call it tbf
